### ISSUE TITLE
Can't open server menu after adding "Hide Sidebar" style

### ISSUE THREAD

**Issue by nuxshed** [nouun/discord-stylus#1]
![Sat Apr  2 08_04_50 AM IST 2022](https://user-images.githubusercontent.com/86704763/161362558-a0763e4f-8256-4925-8df9-fcc303f60cab.jpg)

Expected behaviour: Clicking on the area near "10" should spawn the server menu.
Actual Behaviour: Nothing happens.

Tested after disabling all other styles, and it works fine when this style is disabled.

**Comment by nouun** [comment]
You should be able to update the snippet now and it will be fixed.

**Comment by nuxshed** [comment]
thanks for the quick fix!
